name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: ci
  cancel-in-progress: true
    
jobs:
    macOS:
        name: Test macOS 12
        runs-on: macOS-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: macOS 12
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=macOS" clean test | xcpretty

    iOS_16:
        name: Test iOS 16
        runs-on: macOS-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 16
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 14,OS=16.2" clean test | xcpretty

    iOS_15:
        name: Test iOS 15
        runs-on: macOS-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 15
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 13,OS=15.5" clean test | xcpretty

    iOS_14:
        name: Test iOS 14
        runs-on: macOS-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: iOS 14
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=iOS Simulator,name=iPhone 12,OS=14.5" clean test | xcpretty

    tvOS:
        name: Test tvOS
        runs-on: macos-11
        env:
            DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: tvOS
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=tvOS Simulator,name=Apple TV 4K (at 1080p) (2nd generation),OS=15.2" clean test | xcpretty

    watchOS:
        name: Test watchOS
        runs-on: macOS-12
        env:
            DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: watchOS
              run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme "SwiftUICharts" -destination "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm),OS=9.1" clean test | xcpretty
